### ISSUE TITLE
Preload fails until second time

### ISSUE THREAD

**Issue by KevinSjoberg** [jinzhu/gorm#602]
I've two structs, `Event` and `Planning`. An event has many plannings.

```go
type Event struct {
    ID        int        `json:"id"`
    UserID    int        `json:"user_id"`
    Name      string     `json:"name"`
    CreatedAt time.Time  `json:"created_at"`
    Plannings []Planning `json:"plannings"`
}

type Planning struct {
	ID         int           `json:"id"`
	EventID    int           `json:"event_id"`
	StartAt    time.Time     `json:"start_at"`
	EndAt      time.Time     `json:"end_at"`
	Recurrence sql.NullInt64 `json:"recurrence"`
	CreatedAt  time.Time     `json:"created_at"`
}
```

I also have an API-endpoint setup using [gin](https://github.com/gin-gonic/gin).

```go
func retrieveEvents(c *gin.Context) {
    var events []entities.Event
    db.Preload("Plannings").Where("user_id = ?", 1).Find(&events)
    c.JSON(200, events)
}
```

The **first** time I make a request to the endpoint, I get back events as expected, but `plannings` are `null`. My log spits out `(can't find field Plannings in *[]entities.Event)` and the PostgreSQL log spits out the following:

    LOG:  execute <unnamed>: SELECT  * FROM "events"  WHERE (user_id = $1)
    DETAIL:  parameters: $1 = '1'

The **second** time  (or any request after that) I make a request to the endpoint, I get back events as expected, but this time, `plannings` are set as expected. The log does not spit out any errors and the PostgreSQL log spits out the following:

    LOG:  execute <unnamed>: SELECT  * FROM "events"  WHERE (user_id = $1)
    DETAIL:  parameters: $1 = '1'
    LOG:  execute <unnamed>: SELECT  * FROM "plannings"  WHERE (event_id IN ($1))
    DETAIL:  parameters: $1 = '1'

If you need more details in how to reproduce this, feel free to ping me and I'll give you more context.

**Comment by jaytaylor** [comment]
Providing a full failing unit-test to demonstrate what is broken would be ideal in situations such as this one.

**Comment by KevinSjoberg** [comment]
@jaytaylor absolutely, I'll get to it later today.

**Comment by KevinSjoberg** [comment]
@jinzhu @jaytaylor I'm having a bit of trouble reproducing it as a test case. On the other hand, I've debugged it further and I know see why it fails. The first time, `scope.fields` are already set to an array with all fields except the `plannings` field. The second time `scope.fields` are set accurately to include the `plannings` field as well.

I'm willing to hunt this down further if I can get some pointers to where in the codebase fields are being set initially.

**Comment by ramyala** [comment]
@KevinSjoberg I had the same issue which I solved by adding a DB.AutoMigrate(&ModelA{}, &ModelB{}). The issue seems without automigrate (which I assume you did in your test), the model's associations aren't loaded until first access.

**Comment by KevinSjoberg** [comment]
@ramyala you're correct. Running `db.AutoMigrate(&entities.Event{})` first, resolves the issue. I'd say this is still a bug though, since I don't want nor need the AutoMigrate feature.

**Comment by goddardcm** [comment]
Just started seeing this problem myself after a recent update. I git-bisected to try to figure out with which commit the problem started. I was able to narrow it down to one of these four (can't pinpoint any further because they can't be tested individually due to compilation errors:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
dc428d2364789513875de77ecee30d3af9efbe1c
a29230c86f0849b51bbb3c19b71f108fbb74541d
fea291e796f796d9b9d4ff0305f768c0b3c320d2
4e8272cf9d764be31566aaea0e691816b67df8e0
We cannot bisect more!

Here's a [link] (https://github.com/jinzhu/gorm/compare/2fe185eb77a22a3dbdb42cebed976598162ec294...4e8272cf9d764be31566aaea0e691816b67df8e0#diff-954de6d7c840669472378e118a132334) to the diff of all of those commits.

Hope this helps!

**Comment by KevinSjoberg** [comment]
@goddardcm thanks a lot for this! This will definitely help figuring out what the problem is. I'm going to investigate this even further after work today. :+1:

**Comment by zasran** [comment]
We see the same problem and also can confirm that revision 2fe185e (right before the one reported as first broken) works correctly.

	User struct {
		Id            uint64        `json:"id" gorm:"column:USER_ID;primary_key"`
		// ...
		PhoneNumbers  []PhoneNumber `json:"phoneNumbers" gorm:"foreignkey:UserId"`
	}
	PhoneNumber struct {
		Id     uint64 `json:"id" gorm:"column:PHONE_NUMBER_ID;primary_key"`
		UserId uint64 `json:"userId gorm:"column:USER_ID"`
		// ...
	}
	usersFromDb := []User{}
	db.Preload("PhoneNumbers").Find(&usersFromDb)

results in error with current git code:

(can't find field PhoneNumbers in *[]models.User)

**Comment by jinzhu** [comment]
Hi All,

This issue should be fixed, sorry for the problem.

**Comment by jrdnull** [comment]
Hi @jinzhu, I am having the same issue with the latest revision of gorm. I've created an example where you can reproduce it with a test sqlite db:

https://github.com/jrdnull/gormtest

This is the output:
```
(/Users/jrd/gormtest/main.go:40)
[2015-09-25 09:48:54]  [2.36ms]  SELECT  * FROM "events"

(/Users/jrd/gormtest/main.go:40)
[2015-09-25 09:48:54]  can't find field Plannings in *[]main.Event
2015/09/25 09:48:54 [{ID:1 Plannings:[]} {ID:2 Plannings:[]}]

(/Users/jrd/gormtest/main.go:44)
[2015-09-25 09:48:54]  [0.21ms]  SELECT  * FROM "events"

(/Users/jrd/gormtest/main.go:44)
[2015-09-25 09:48:54]  [0.40ms]  SELECT  * FROM "plannings"  WHERE (event_id IN ('1','2'))
2015/09/25 09:48:54 [{ID:1 Plannings:[{ID:1 EventID:1} {ID:2 EventID:1}]} {ID:2 Plannings:[{ID:3 EventID:2}]}]
```

Let me know if you need anymore info

**Comment by jinzhu** [comment]
Hi @jrdnull 

Thank you for your script a lot, found the problem, and just fixed that.

Thank you.

**Comment by jrdnull** [comment]
Thanks for fixing that so quickly @jinzhu, really enjoying gorm so far. Tested in my project and works great now :+1:

**Comment by awishformore** [comment]
Hello @jinzhu 

Our team has started working with gorm a lot, and it is overall an enjoyable experience.

Unfortunately, we ran into this exact bug. Even more unfortunately, I can't seem to create a test case to reproduce the issue, so I will describe it as best as I can:

- accounts have customers which have subscriptions
- users have contacts which have subscriptions
-  a subscription has exactly one user and one customer


**From the account side, the relations look like this:**

Account has a slice of Customer as one-to-many relationship.
Customer has an AccountID and an Account for this.

Customer has a slice of Subscriptions as one-to-many relationship.
Subscription has a CustomerID and a Customer for this.


**From the user side, things are exactly the same:**

User has a slice of Contact as one-to-many relationship.
Contact has an UserID and a User for this.

Contact has a slice of Subscriptions as one-to-many relationship.
Subscription has a ContactID and a Contact for this.


** Where things get weird... **

We use preload for two queries:

db.Preload("Customers.Subscriptions").Find(&account)
db.Preload("Contacts.Subscriptions").Find(&user)

The error we encounter is: (can't find field Subscriptions in *[]Customer)

We tried everything from renaming, changing tags, removing fields, and in the end it all comes down to this:

1) If we simply remove the Customer struct field in Subscription, it *works*. Not the CustomerID, and not anything else from other relations, only the Customer struct field.

2) If we remove the Contact struct field, it *doesn't work*. Not even if we remove everything else except for the foreign IDs of oter relations.

3) Executing the same preload more than once does *not* solve the issue.

4) The issue does not exist in revision 2fe185e, as mentioned before. In other words, revision 2fe185e works fine.

It's really confusing because structurally, Customer and Contact can be *exactly* the same, and it still will work for Contact, but not for Customer. We even tried renaming everything, changing all the tags, and so on.

I will try to come up with a test case that actually shows this bug, but for now, after two days of investigating, I don't have the time anymore and we will just remove the customer reference and manually load it from ID as a workaround.

**Comment by murz** [comment]
@jinzhu,

I am also experiencing this bug still with the latest code. Here is a simple code example to reproduce it:
```
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/lib/pq"
	"log"
)

type Foo struct {
	ID int
	Bar Bar
	BarID int
}

type Bar struct {
	ID int
	Foos []Foo
}

func main() {
	DB, err := gorm.Open("postgres", "postgres://nourishdb:nour1sh@192.168.99.100:5432/nourish?sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}
	DB.AutoMigrate(&Foo{}, &Bar{})
	var bars []*Bar
	if err := DB.Preload("Foos").Find(&bars).Error; err != nil {
		log.Fatal(err)
	}
	log.Println(bars)
}
```

When I run this code as is I get the following error:
```
$ go run main.go 
2015/12/16 20:05:49 can't find field Foos in *[]*main.Bar
exit status 1
```

And just like @awishformore pointed out, if you simply remove the Bar struct field from Foo then it works.

**Comment by jinzhu** [comment]
Hi @murz 

Thank you for your report, this should been fixed, thank you for your check.
